name: Build Container & Run

on: [pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gymcorp-squad39

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Commit short tag
        id: tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          content: .
          file: ./Dockerfile
          tags: gymcorp/gymcorp-squad39:${{ steps.tag.outputs.sha_short }}
          outputs: type=docker,dest=/tmp/img.tar

      - name: Upload for testing
        uses: actions/upload-artifact@v2
        with:
          name: gymcorp-squad39-${{ steps.tag.outputs.sha_short }}
          path: /tmp/img.tar
          retention-days: 1
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Commit short tag
        id: tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
      - name: Download built container
        uses: actions/download-artifact@v2
        with:
          name: gymcorp-squad39-${{ steps.tag.outputs.sha_short }}
          path: /tmp
      - name: Test General Use is shown on /activities
        run: |
          docker load --input /tmp/img.tar
          docker run --rm -d -v /tmp/gymcorp:/data -p 5000:5000 -e GYMCORP_POPULATE=1 -e GYMCORP_POPULATE_NOSTRIPE=1 -e GYMCORP_NOSSL=1 gymcorp/gymcorp-squad39:${{ steps.tag.outputs.sha_short }}
          sleep 10
          curl http://localhost:5000/activities | grep General
  
  cleanup:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Commit short tag
        id: tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: gymcorp-squad39-${{ steps.tag.outputs.sha_short }}



